theme="catppuccin_latte"
[editor.lsp]
display-inlay-hints = true
display-messages = true

[keys.insert]
C-c = "normal_mode"
[keys.select]
C-c = "normal_mode"
[keys.normal]
C-s = ":w"


[editor]
true-color = true
cursorline = true
bufferline = "multiple"
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
auto-format = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

