theme = "catppuccin_latte"
[editor]
true-color = true
auto-format = true
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.lsp]
display-inlay-hints = true
display-messages = true

[keys.insert.j]
k = "normal_mode"
[keys.select.j]
k = "normal_mode"
