theme = "catppuccin_latte"
[editor]
true-color = true
auto-format = true
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.lsp]
display-inlay-hints = true
display-messages = true

[keys.insert]
C-c = "normal_mode"
[keys.select]
C-c = "normal_mode"
"C-ret" = "toggle_comments"